import cv2

img = cv2.imread('mountain.jpg')
cv2.namedWindow('BGR', cv2.WINDOW_NORMAL)
cv2.imshow('BGR', img)
blue, green, red = cv2.split(img)
cv2.namedWindow('BGR_B', cv2.WINDOW_NORMAL)
cv2.imshow('BGR_B', blue)
cv2.namedWindow('BGR_G', cv2.WINDOW_NORMAL)
cv2.imshow('BGR_G', green)
cv2.namedWindow('BGR_R', cv2.WINDOW_NORMAL)
cv2.imshow('BGR_R', red)
print(f'BGR影像shape屬性={img.shape}')
print(f'BGR_B影像shape屬性={blue.shape}')
print(f'BGR_G影像shape屬性={green.shape}')
print(f'BGR_R影像shape屬性={red.shape}')
cv2.waitKey(0)
cv2.destroyAllWindows()
